welcome:
  message: Welcome to Fazal Tuts4U!!!

server:
  port: 9000

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/user-registration
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
